"""Add advanced DLP policy management models

Revision ID: f6234ac89eb7
Revises: c511e97582d2
Create Date: 2025-10-12 19:01:26.041999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6234ac89eb7'
down_revision = 'c511e97582d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_audit_events', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('admin_audit_events', 'admin_user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('audit_events', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('audit_events', 'actor_user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=True)
    op.alter_column('chat_sessions', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('chat_sessions', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('dlp_entity_configs', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('dlp_entity_configs', 'created_by',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=True)
    op.add_column('dlp_policies', sa.Column('parent_rule_id', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('dlp_policies', sa.Column('rule_group', sa.String(), nullable=True))
    op.add_column('dlp_policies', sa.Column('conditions', sa.JSON(), nullable=True))
    op.add_column('dlp_policies', sa.Column('schedule', sa.JSON(), nullable=True))
    op.add_column('dlp_policies', sa.Column('tags', sa.JSON(), nullable=True))
    op.alter_column('dlp_policies', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('dlp_policies', 'created_by',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=True)
    op.create_foreign_key(None, 'dlp_policies', 'dlp_policies', ['parent_rule_id'], ['id'])
    op.alter_column('dlp_policy_groups', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('dlp_policy_groups', 'created_by',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=True)
    op.alter_column('dlp_rule_templates', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('dlp_rule_templates', 'created_by',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=True)
    op.alter_column('dlp_user_exceptions', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('dlp_user_exceptions', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('dlp_user_exceptions', 'created_by',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('dlp_user_exceptions', 'approved_by',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=True)
    op.alter_column('dlp_violation_logs', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('dlp_violation_logs', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('dlp_violation_logs', 'session_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=True)
    op.alter_column('dlp_violation_logs', 'message_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=True)
    op.alter_column('ldap_users_temp', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('litellm_keys', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('messages', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('messages', 'session_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('messages', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('session_analytics', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('session_analytics', 'session_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('session_analytics', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('system_configs', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('user_roles', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('user_roles', 'user_id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('system_configs', 'id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('session_analytics', 'user_id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('session_analytics', 'session_id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('session_analytics', 'id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('messages', 'user_id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('messages', 'session_id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('messages', 'id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('litellm_keys', 'id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('ldap_users_temp', 'id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('dlp_violation_logs', 'message_id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('dlp_violation_logs', 'session_id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('dlp_violation_logs', 'user_id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('dlp_violation_logs', 'id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('dlp_user_exceptions', 'approved_by',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('dlp_user_exceptions', 'created_by',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('dlp_user_exceptions', 'user_id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('dlp_user_exceptions', 'id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('dlp_rule_templates', 'created_by',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('dlp_rule_templates', 'id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('dlp_policy_groups', 'created_by',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('dlp_policy_groups', 'id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_constraint(None, 'dlp_policies', type_='foreignkey')
    op.alter_column('dlp_policies', 'created_by',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('dlp_policies', 'id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('dlp_policies', 'tags')
    op.drop_column('dlp_policies', 'schedule')
    op.drop_column('dlp_policies', 'conditions')
    op.drop_column('dlp_policies', 'rule_group')
    op.drop_column('dlp_policies', 'parent_rule_id')
    op.alter_column('dlp_entity_configs', 'created_by',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('dlp_entity_configs', 'id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('chat_sessions', 'user_id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('chat_sessions', 'id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('audit_events', 'actor_user_id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('audit_events', 'id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('admin_audit_events', 'admin_user_id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('admin_audit_events', 'id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    # ### end Alembic commands ###